# Generated by Django 5.2 on 2025-04-26 15:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_client_solde_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Le nom de la boutique', max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('identite_commerciale', models.CharField(choices=[('Fashion', 'Fashion'), ('Maquillage', 'Maquillage'), ('Beauty', 'Beauty'), ('Décoration', 'Décoration'), ('Électroménager', 'Électroménager'), ('Électronique', 'Électronique'), ('Accessoire', 'Accessoire')], max_length=20, verbose_name='Identité commerciale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('marchand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to='users.marchand', verbose_name='Marchand')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'db_table': 'boutiques',
            },
        ),
    ]
