# Generated by Django 5.2 on 2025-04-29 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='marchand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to='users.marchand', verbose_name='Marchand'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='category_boutique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to='boutique.categoryboutique', verbose_name='Catégorie Boutique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.boutique', verbose_name='Boutique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='category_produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.categoryproduit', verbose_name='Catégorie Produit'),
        ),
    ]
