# Generated by Django 5.2 on 2025-04-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boutique_images/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Le nom de la catégorie', max_length=255, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Image')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='boutique.boutique', verbose_name='Boutique')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Le nom du produit', max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('couleur', models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur')),
                ('taille', models.CharField(blank=True, max_length=50, null=True, verbose_name='Taille')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.boutique', verbose_name='Boutique')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'produits',
            },
        ),
    ]
