# Generated by Django 5.2 on 2025-05-01 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduit',
            name='boutique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_produits', to='boutique.boutique', verbose_name='Boutique'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='boutique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.boutique', verbose_name='Boutique'),
        ),
    ]
