# Generated by Django 5.2 on 2025-04-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_boutique_image_category_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produit_images/', verbose_name='Image'),
        ),
    ]
