# Generated by Django 5.2 on 2025-04-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_alter_produit_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.RenameField(
            model_name='boutique',
            old_name='identite_commerciale',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='boutique',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
