# Generated by Django 5.2 on 2025-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_categoryproduit_boutique_alter_produit_boutique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='boutique_logos/', verbose_name='Logo'),
        ),
    ]
