# Generated by Django 5.2 on 2025-05-03 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_alter_boutique_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='image',
            field=models.ImageField(blank=True, upload_to='boutique_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.ImageField(blank=True, upload_to='boutique_logos/', verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='Echange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to='boutique.boutique')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Échange',
                'verbose_name_plural': 'Échanges',
                'db_table': 'echanges',
            },
        ),
    ]
