# Generated by Django 5.2 on 2025-04-27 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_boutique_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Boutique',
                'verbose_name_plural': 'Catégories de Boutiques',
                'db_table': 'categories_boutiques',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_produit_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Produit',
                'verbose_name_plural': 'Catégories de Produits',
                'db_table': 'categories_produits',
            },
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='boutique',
            name='Category',
        ),
        migrations.AlterField(
            model_name='boutique',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='category_boutique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.categoryboutique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='category_produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.categoryproduit', verbose_name='Catégorie Produit'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
