# Generated by Django 5.2 on 2025-04-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_categoryboutique_categoryproduit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='category_boutique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to='boutique.categoryboutique', verbose_name='Catégorie Boutique'),
        ),
    ]
