# Generated by Django 5.2 on 2025-05-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_alter_boutique_image_alter_boutique_logo_echange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='boutique',
        ),
    ]
