# Generated by Django 5.2 on 2025-05-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='shop',
            new_name='boutique',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
