# Generated by Django 5.2 on 2025-04-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adresse',
        ),
    ]
