# Generated by Django 5.2 on 2025-05-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchand',
            name='is_marchant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admins',
        ),
    ]
