# Generated by Django 5.2 on 2025-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='historique_achats',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='solde_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marchand',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='marchand',
            name='entreprise_nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='marchand',
            table='marchands',
        ),
    ]
