# Generated by Django 5.2 on 2025-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_marchand_boutique_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchand',
            name='description',
        ),
        migrations.AddField(
            model_name='marchand',
            name='is_marchant',
            field=models.BooleanField(default=False),
        ),
    ]
