# Generated by Django 5.2 on 2025-04-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_historique_achats_client_solde_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='solde_points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
