# Generated by Django 5.2 on 2025-04-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_solde_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchand',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='marchand',
            name='entreprise_nom',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
