# Generated by Django 5.2 on 2025-04-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_marchand_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marchand',
            old_name='entreprise_nom',
            new_name='boutique_nom',
        ),
    ]
