# Generated by Django 5.2 on 2025-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_admin_user_ptr_remove_client_user_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('marchand', 'Marchand'), ('admin', 'Admin')], max_length=10),
        ),
    ]
