# Generated by Django 5.2 on 2025-05-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('marchand', 'Marchand'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
