# Generated by Django 5.2 on 2025-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_admin_user_alter_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='historique_achats',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='solde_points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
